# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VAIui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VAIGUI(object):
    def setupUi(self, VAIGUI):
        VAIGUI.setObjectName("VAIGUI")
        VAIGUI.resize(822, 622)
        self.centralwidget = QtWidgets.QWidget(VAIGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 821, 621))
        self.label.setStyleSheet("background-color: rgba(0, 255, 0, 0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/HP/Downloads/Imarticus/Python/VAI/7LP8.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 470, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 470, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(90, 20, 256, 41))
        self.textBrowser.setStyleSheet("background: transparent;\n"
        "border-radius:none;\n"
        "color:white;\n"
        "font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(340, 20, 256, 41))
        self.textBrowser_2.setStyleSheet("background: transparent;\n"
        "border-radius:none;\n"
        "color:white;\n"
        "font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        VAIGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(VAIGUI)
        QtCore.QMetaObject.connectSlotsByName(VAIGUI)

    def retranslateUi(self, VAIGUI):
        _translate = QtCore.QCoreApplication.translate
        VAIGUI.setWindowTitle(_translate("VAIGUI", "MainWindow"))
        self.pushButton.setText(_translate("VAIGUI", "RUN"))
        self.pushButton_2.setText(_translate("VAIGUI", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VAIGUI = QtWidgets.QMainWindow()
    ui = Ui_VAIGUI()
    ui.setupUi(VAIGUI)
    VAIGUI.show()
    sys.exit(app.exec_())
